spring.application.name=graceful-shutdown
server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=30s
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
